### ISSUE TITLE
Add Mattermost Webhook integration

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#495]
- deprecate slack
- add mattermost webhook for build success, fail, etc.

**Comment by stefanjauker** [comment]
+1

**Comment by gruppjo** [comment]
Other tasks:

- integrate into demo repo
- delete old slack integration https://m-wayteam.slack.com/apps/A0F81FP4N-travis-ci
- make sure everything works as expected, onchange: repo, demo, master, dev, PRs

**Comment by MathiasTim** [comment]
I have just deleted the old Slack integration

**Comment by gruppjo** [comment]
Die Webhook Integration von Mattermost muss angepasst werden, da das Übergabe Format anders aussieht als aktuell eingerichtet.

Der Channel reagiert auf:
```sh
curl -i -X POST -d 'payload={"text": "Hello, this is some text.\nThis is more text."}' https://mattermost.mwaysolutions.com/hooks/7b794wboitdaxrzjkxcjt3enjr
```

Das Travis Format hat aber keine `text` property sieht aber folgendermaßen aus: https://docs.travis-ci.com/user/notifications/#Webhooks-Delivery-Format
```json
{
  "id": 1,
  "number": "1",
  "status": null,
  "started_at": null,
  "finished_at": null,
  "status_message": "Passed",
  "commit": "62aae5f70ceee39123ef",
  "branch": "master",
  "message": "the commit message",
  "compare_url": "https://github.com/svenfuchs/minimal/compare/master...develop",
  "committed_at": "2011-11-11T11: 11: 11Z",
  "committer_name": "Sven Fuchs",
  "committer_email": "svenfuchs@artweb-design.de",
  "author_name": "Sven Fuchs",
  "author_email": "svenfuchs@artweb-design.de",
  "type": "push",
  "build_url": "https://travis-ci.org/svenfuchs/minimal/builds/1",
  "repository": {
    "id": 1,
    "name": "minimal",
    "owner_name": "svenfuchs",
    "url": "http://github.com/svenfuchs/minimal"
   },
  "config": {
    "notifications": {
      "webhooks": ["http://evome.fr/notifications", "http://example.com/"]
    }
  },
  "matrix": [
    {
      "id": 2,
      "repository_id": 1,
      "number": "1.1",
      "state": "created",
      "started_at": null,
      "finished_at": null,
      "config": {
        "notifications": {
          "webhooks": ["http://evome.fr/notifications", "http://example.com/"]
        }
      },
      "status": null,
      "log": "",
      "result": null,
      "parent_id": 1,
      "commit": "62aae5f70ceee39123ef",
      "branch": "master",
      "message": "the commit message",
      "committed_at": "2011-11-11T11: 11: 11Z",
      "committer_name": "Sven Fuchs",
      "committer_email": "svenfuchs@artweb-design.de",
      "author_name": "Sven Fuchs",
      "author_email": "svenfuchs@artweb-design.de",
      "compare_url": "https://github.com/svenfuchs/minimal/compare/master...develop"
    }
  ]
}
```
Ich habe Sascha gefragt ob er mir die Rechte geben kann, um den Hook anzupassen.

**Comment by gruppjo** [comment]
I'm turning the slack integration back on for now:

generator-m-ionic:
```yml
sudo: false
language: node_js
env: CI=true
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
notifications:
  email: false
  slack:
    rooms:
      - m-wayteam:id3DFokHndVEGtjOM9fR0DVj#generator-m-services
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87130ded51c12384d4e7
      - https://mattermost.mwaysolutions.com/hooks/7b794wboitdaxrzjkxcjt3enjr
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

```

generator-m-ionic-demo:
```js
sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
before_install:
  - npm install -g bower
install:
  - npm install
  - bower install
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - npm i -g npm@^3
#   - sleep 3 # give xvfb some time to start
notifications:
  email: false
  slack:
    rooms:
      - m-wayteam:id3DFokHndVEGtjOM9fR0DVj#generator-m-services
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
```
